version: '3'
services:
  pig-ui:
    build:
      context: .
    restart: always
    container_name: pig-ui
    image: pauly.fun:8009/pig-ui
    ports:
      - 8005:80
    volumes:
      - /root/nginx/certs:/etc/nginx/certs
    extra_hosts:
      - "pig-gateway:192.168.0.110"